//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET_MVC_Bootstrap4_Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contenu()
        {
            this.Seances = new HashSet<Seance>();
            this.Acteurs = new HashSet<Acteur>();
            this.Directeurs = new HashSet<Directeur>();
            this.Genres = new HashSet<Genre>();
        }
    
        public string Titre { get; set; }
        public string Description { get; set; }
        public int Annee { get; set; }
        public int RuntimeMins { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> Votes { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<int> MetaScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acteur> Acteurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Directeur> Directeurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
