//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineLogic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineDBEntities : DbContext
    {
        public CineDBEntities()
            : base("name=CineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acteur> Acteurs { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<Contenu> Contenus { get; set; }
        public virtual DbSet<Directeur> Directeurs { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Responsable> Responsables { get; set; }
        public virtual DbSet<Salle> Salles { get; set; }
        public virtual DbSet<ContenuPromo> ContenuPromoes { get; set; }
        public virtual DbSet<Seance> Seances { get; set; }
        public virtual DbSet<SeanceContenu> SeanceContenus { get; set; }
        public virtual DbSet<SeancePromo> SeancePromoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ContenuPromo> ContenuPromoes { get; set; }
        public virtual DbSet<SeanceContenu> SeanceContenus { get; set; }
        public virtual DbSet<SeancePromo> SeancePromoes { get; set; }
    }
}
