//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contenu()
        {
            this.Seances = new HashSet<Seance>();
            this.Acteurs = new HashSet<Acteur>();
            this.Directeurs = new HashSet<Directeur>();
            this.Genres = new HashSet<Genre>();
            this.SeanceContenus = new HashSet<SeanceContenu>();
        }
    
        public string Titre { get; set; }
        public string Description { get; set; }
        public int Annee { get; set; }
        public int RuntimeMins { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> Votes { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<int> MetaScore { get; set; }
        public string typage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acteur> Acteurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Directeur> Directeurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeanceContenu> SeanceContenus { get; set; }
    }
}
