//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seance
    {
        public int SeanceID { get; set; }
        public string Titre { get; set; }
        public System.DateTime HeureDebut { get; set; }
        public System.DateTime HeureFin { get; set; }
        public int SalleID { get; set; }
        public string ContenuTitre { get; set; }
    
        public virtual Contenu Contenu { get; set; }
        public virtual Salle Salle { get; set; }
    }
}
