//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeancePromo
    {
        public string PromoTitre { get; set; }
        public int SeanceID { get; set; }
        public Nullable<int> indexOrdre { get; set; }
    
        public virtual ContenuPromo ContenuPromo { get; set; }
        public virtual Seance Seance { get; set; }
    }
}
